Fix week identifying
kreslavskiy/Schedule-bot pull request #11
Opened 2023-10-08 22:05 UTC by MrPaschenko

2023-10-25 19:41 UTC, kreslavskiy requested changes

2023-10-25 19:41 UTC, kreslavskiy commented on api/api.js
> +currentTime();
Это зачем?

2023-10-25 19:41 UTC, kreslavskiy commented on api/api.js
> +    case 0:
Перепиши эту мерзость со свич-кейсами на что-то более адекватное

2023-10-28 11:24 UTC, MrPaschenko commented on api/api.js
> +    case 0:
Deleted

2023-10-28 11:24 UTC, MrPaschenko commented on api/api.js
> +currentTime();
Deleted

2023-10-28 11:29 UTC, MrPaschenko commented on api/api.js
> +    case 0:
Done

2023-10-29 11:28 UTC, kreslavskiy approved these changes

2023-10-29 11:28 UTC, merged